services:
  keycloak-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak-assistant
    ports:
      - "8888:8888"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8888
    volumes:
      - ./Data:/app/data
      # SSL сертификаты копируются в образ, не монтируем
    restart: unless-stopped
    networks:
      - keycloak_default

networks:
  keycloak_default:
    external: true
